name: CI + CD

on:
#  push:
#    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Build Project
         working-directory: env_test_app
         run: |
          cd env_test_app
          npm run build

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    environment:
      name: DEV
      url: http://dev.myapp.com
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
          
      - name: Install Dependencies
        # working-directory: ./env_test_app
        run: |
          cd env_test_app
          npm install
        
      - name: Build Project
        # working-directory: ./env_test_app
        run: |
          cd env_test_app
          npm run build
