name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0" # specify the required Node.js version

      - name: Install dependencies
        run: |
          cd env_test_app
          npm install

      - name: Build project
        run: |
          cd env_test_app
          npm run build
