name: Sample CI + CD Pipeline

on:
  push:
    branches:
      - main2
  pull_request:
    branches:
      - main2
  workflow_dispatch:
    inputs:
      Env:
        description: "Select environment (DEV or PROD)"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - PROD
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.5.0'

      - name: Install Dependencies
        run: npm install --prefix env_test_app

      - name: Echo TEST Value
        run: echo "TEST value is ${{ vars.TEST }}"
        env:
          TEST: ${{ vars.TEST }}

      - name: Build Project
        run: npm run build --prefix env_test_app
        env:
          TEST: ${{ vars.TEST }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.Env == 'DEV' }}
    environment: DEV  # This links the job to the DEV environment
    steps:
      - name: Echo TEST Value in DEV
        run: echo "Deploying to DEV environment with TEST value ${{ vars.TEST }}"
        env:
          TEST: ${{ vars.TEST }}

      - name: Echo WEBSITE_ENV_DEV Value in DEV
        run: echo "${{ vars.WEBSITE_ENV_DEV }}" > .env  
     
      - name: Deploy DEV
        run: echo 'Deploying to DEV environment'
        env:
          TEST: ${{ vars.TEST }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ vars.GHCR_PAT }} | docker login ghcr.io --username ${{ vars.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t ghcr.io/${{ vars.GHCR_USERNAME }}/test_app:1.0.0 -f env_test_app/Dockerfile --build-arg ENV_FILE=.env --load env_test_app

      - name: Tag Docker image
        run: docker tag ghcr.io/${{ vars.GHCR_USERNAME }}/test_app:1.0.0 ghcr.io/test_app:1.0.0

      - name: Push Docker image
        run: docker push ghcr.io/test_app:1.0.0

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    environment: PROD  # This links the job to the PROD environment
    steps:
      - name: Echo TEST Value in PROD
        run: echo "Deploying to PROD environment with TEST value ${{ vars.TEST }}"
        env:
          TEST: ${{ vars.TEST }}

      - name: Deploy PROD
        run: echo 'Deploying to PROD environment'
        env:
          TEST: ${{ vars.TEST }}
