name: CI + CD Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV  # Link to the environment where TEST is defined
    env:
      TEST: ${{ env.TEST }}  # Ensure the TEST variable is set correctly
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install Dependencies
        working-directory: env_test_app
        run: npm install

      - name: Echo TEST Value
        working-directory: env_test_app
        run: echo "TEST value is $TEST"

      - name: Build Project
        working-directory: env_test_app
        run: npm run build

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    environment: DEV  # This links the job to the DEV environment
    env:
      TEST: ${{ env.TEST }}  # Ensure the TEST variable is set correctly!
    steps:
      - name: Echo TEST Value in DEV
        run: echo "Deploying to DEV environment with TEST value $TEST"

      - name: Deploy DEV
        run: echo 'Deploying to DEV environment'

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    environment: PROD  # This links the job to the PROD environment
    env:
      TEST: ${{ env.TEST }}  # Ensure the TEST variable is set correctly
    steps:
      - name: Echo TEST Value in PROD
        run: echo "Deploying to PROD environment with TEST value $TEST"

      - name: Deploy PROD
        run: echo 'Deploying to PROD environment'
