name: Echo Environment Variable

on:
  workflow_dispatch:
    inputs:
      Env:
        description: "Select environment (DEV or PROD)"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - PROD

jobs:
  echo-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set TEST variable based on selected ENV
        run: |
          if [ "${{ github.event.inputs.Env }}" == "DEV" ]; then
            TEST="${{ vars.TEST }}"
          elif [ "${{ github.event.inputs.Env }}" == "PROD" ]; then
            TEST="${{ vars.TEST }}"
          else
            echo "Invalid ENV value"
            exit 1
          fi
          echo "TEST variable value: $TEST"
