name: Echo Environment Variable

on:
  workflow_dispatch:
    inputs:
      Env:
        description: "Select environment (DEV or PROD)"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - PROD

jobs:
  echo-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set TEST variable based on selected ENV
        run: |
          if [ "${{ github.event.inputs.Env }}" == "DEV" ]; then
            echo "TEST=${{ vars.DEV_TEST }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.Env }}" == "PROD" ]; then
            echo "TEST=${{ vars.PROD_TEST }}" >> $GITHUB_ENV
          else
            echo "Invalid ENV value"
            exit 1
          fi

      - name: Echo the TEST environment variable
        run: echo "TEST variable value $TEST"
